Pr
khan0531/first-project pull request #13
Opened 2023-10-14 06:43 UTC by khan0531

### 변경사항

**AS-IS**
도메인 추가
문의&리뷰 작성 및 수정 api 
**TO-BE**

### 테스트
 
- [ ] 테스트 코드
- [ ] API 테스트

2023-10-14 07:28 UTC, lazyflavor commented on src/main/java/com/beauty/api/model/user/dto/MemberSignUpRequest.java
>    private String phone;
@NotBlank(message = "전화번호를 입력해주세요.")
@Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "올바른 전화번호 형식이 아닙니다.")
private String phone;

2023-10-14 07:30 UTC, lazyflavor reviewed
리뷰 드려봤습니다.

2023-10-16 04:50 UTC, syoh0708 requested changes

2023-10-16 04:50 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/inquiry/controller/InquiryController.java
> +  public ResponseEntity<?> updateInquiry(@AuthenticationPrincipal Member member, @PathVariable Long inquiryId,
```suggestion
  @PatchMapping("/{id}")
  public ResponseEntity<?> updateInquiry(@AuthenticationPrincipal Member member, @PathVariable Long id,
```

2023-10-16 04:50 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/inquiry/controller/InquiryController.java
> +  @PostMapping("/inquiry")
```suggestion
  @PostMapping
```

2023-10-16 04:50 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/inquiry/domain/Inquiry.java
> +    return this.member.getId().equals(member.getId());
Optional로 처리해주면 좋음

2023-10-16 04:50 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/inquiry/service/InquiryService.java
>      if (inquiryEntities.size() > 0) {
AnyMatch 사용하면 좋을 듯

2023-10-16 04:50 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/inquiry/controller/InquiryController.java
> +
여기서 member id와 inquiryRequest의 member id validate하자

2023-10-16 04:50 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/review/controller/ReviewController.java
> +    if (!Objects.equals(reviewId, reviewUpdateRequest.getId())) {
```suggestion
  @PatchMapping("/{id}")
  public ResponseEntity<?> updateReview(@AuthenticationPrincipal Member member,
      @PathVariable Long id, @RequestBody ReviewUpdateRequest reviewUpdateRequest) {

    if (!Objects.equals(id, reviewUpdateRequest.getId())) {
```

2023-10-16 04:50 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/review/service/ReviewService.java
>          });
reservation status도 체크해야할 듯

2023-10-16 04:50 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/user/controller/AdminMemberController.java
> +    );
generateToken signature를 UserDetails 넣는 게 좋아보임

2023-10-16 04:50 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/reservation/domain/Reservation.java
> +    }
validation이 ReservationRequest에 있는 게 좋은 것 같다

2023-10-16 05:15 UTC, khan0531 commented on src/main/java/com/beauty/api/model/user/dto/MemberSignUpRequest.java
>    private String phone;
감사합니다!

2023-10-16 05:56 UTC, merged