Membaer signup
khan0531/first-project pull request #4
Opened 2023-10-07 05:26 UTC by khan0531

서비스, 컨트롤러 구현
관련 dto: MemberResponse, Member

### 변경사항

**AS-IS**
회원 로그인 구현
**TO-BE**

### 테스트
 
- [ ] 테스트 코드
- [ ] API 테스트

2023-10-09 04:40 UTC, syoh0708 requested changes

2023-10-09 04:40 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/user/dto/Member.java
>  public class Member {
이름 바꾸는 게 좋을듯 MemberRequest, SignUpRequest 같은 거?

2023-10-09 04:40 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/user/controller/MemberController.java
> +    var result = this.memberService.signUp(member);
Return Type

2023-10-09 04:40 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/user/controller/MemberController.java
> +    var result = this.memberService.signIn(memberSigninReQuest);
return type

2023-10-09 04:40 UTC, syoh0708 commented on src/main/java/com/beauty/api/model/user/dto/MemberSigninReQuest.java
> +public class MemberSigninReQuest {
MemberSignInRequest

2023-10-10 13:44 UTC, mingming-mentor approved these changes
리뷰드렸습니다. 수고 많으셨어요

2023-10-10 13:44 UTC, mingming-mentor commented on src/main/java/com/beauty/api/model/user/dto/MemberSignUpRequest.java
> +  private String email;
MemberUpdateRequest 에서는 @Email이 달려있는데요, 여기도 동일하게 어노테이션 달아주시면 좋을 것 같아요

2023-10-10 13:44 UTC, mingming-mentor commented on src/main/java/com/beauty/api/model/user/persist/entity/AdminMemberEntity.java
> +  @Email(message = "이메일 형식이 아닙니다.")
entity에 javax validation을 단 이유가 있을까요?

2023-10-10 13:44 UTC, mingming-mentor commented on src/main/java/com/beauty/api/model/user/persist/entity/AdminMemberEntity.java
> +public class AdminMemberEntity implements UserDetails {
entity와 UserDetail은 분리해주시면 좋을 것 같습니다. 
entity는 DB의 column을 데이터로 가지고오기위해 필요한 class이고 (row에 맵핑되는 구조를 가진 클래스)
JPA를 사용하시는 만큼 entity manager에 의해 관리되기 때문에 데이터가 proxy로 들어가 있을수도 있어요. 그리고 설정에 따라 데이터를 사용할때 쿼리가 새롭게 나가기도 하는데 불필요하게 쿼링될 경우도 생깁니다.
UserDetails를 사용하는 목적과 맞지 않기 때문에 user detail은 별도의 dto클래스를 만들어 구현해주세요

2023-10-10 13:44 UTC, mingming-mentor commented on src/main/java/com/beauty/api/model/user/service/MemberService.java
> +    }
별도로 선언할 필요없이 합쳐도 될듯 합니다

2023-10-10 13:44 UTC, mingming-mentor commented on src/main/java/com/beauty/api/model/user/controller/MemberController.java
> +  @PatchMapping
현재 구현에서는 memberUpdateRequest로 들어오는 데이터를 그대로 저장하는 형태인것 같아요. 이럴경우 PutMapping을 써주시는 것이 맞습니다. 
https://papababo.tistory.com/entry/HTTP-METHOD-PUT-vs-PATCH-%EC%B0%A8%EC%9D%B4%EC%A0%90

2023-10-10 13:44 UTC, mingming-mentor commented on src/main/java/com/beauty/api/security/JwtAuthenticationFilter.java
> +      log.info(String.format("[%s] -> %s", this.tokenProvider.getUsername(token), request.getRequestURI()));
`log.info("{} -> {}", this.tokenProvider.getUsername(token), request.getRequestURI());
`이렇게 작성해주셔도 됩니다

2023-10-11 07:30 UTC, khan0531 commented on src/main/java/com/beauty/api/model/user/persist/entity/AdminMemberEntity.java
> +  @Email(message = "이메일 형식이 아닙니다.")
javax validation은 entity가 아닌 dto에 다는게 정석일까요?

2023-10-11 07:54 UTC, merged

2023-10-12 04:32 UTC, khan0531 commented on src/main/java/com/beauty/api/model/user/persist/entity/AdminMemberEntity.java
> +public class AdminMemberEntity implements UserDetails {
@mingming-mentor 
리뷰 감사드립니다.
일단 머지하고 리뷰주신 부분에 대해 작업하는 중에 질문드립니다.
데이터가 프록시로 들어가 있을 수도 있다는 말이 무슨 뜻인가요?

2023-10-12 14:53 UTC, mingming-mentor commented on src/main/java/com/beauty/api/model/user/persist/entity/AdminMemberEntity.java
> +public class AdminMemberEntity implements UserDetails {
@khan0531 님 https://tecoble.techcourse.co.kr/post/2022-10-17-jpa-hibernate-proxy/ 참고해보시면 좋을 것 같아요.